name: QMK Layout build
on:
  workflow_dispatch:
  push:
    paths:
      - "keyboards/**"
      - ".github/workflows/*"
      - "*.c"
      - "*.h"

jobs:
  list-user-keymaps:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: echo "matrix=$(find keyboards -regex ".*keymaps" | sed "s|keyboards/\(.*\)/keymaps|\1|"| jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
      - run: echo $GITHUB_OUTPUT

  convert-layout:
    name: Convert QMK Layout
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    needs: list-user-keymaps
    strategy:
      fail-fast: false
      matrix:
        keyboards: ${{ fromJson(needs.list-user-keymaps.outputs.matrix) }}
    env:
      USERSPACE_PATH: users/${{ github.actor }}
    steps:
      - name: Disable git safe directory checks
        run: git config --global --add safe.directory '*'

      - name: Checkout QMK
        uses: actions/checkout@v4
        with:
          repository: qmk/qmk_firmware
          ref: master
          submodules: true

      # path is relative to github.workspace
      - name: Checkout userspace
        uses: actions/checkout@v4
        with:
          path: ${{ env.USERSPACE_PATH }}
          persist-credentials: false

      - name: Copy users/keyboards/* to keyboards/*
        run: cp -rfv ${{ env.USERSPACE_PATH }}/keyboards/* keyboards/

      - name: Convert Layout
        run: |
          qmk c2json \
            -o $(echo ${{ matrix.keyboards }} | tr / -).json \
            -kb ${{ matrix.keyboards }} \
            -km ${{ github.actor }} \
            keyboards/${{ matrix.keyboards }}/keymaps/${{ github.actor }}/keymap.c --no-cpp

      - name: Upload Layout
        uses: actions/upload-artifact@v4
        with:
          name: qmk-layout-artifact-${{ github.run_number }}
          path: |
            *.hex
            *.json

  render-keymap:
    name: Keymap Drawer
    needs: [list-user-keymaps, convert-layout]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        keyboards: ${{ fromJson(needs.list-user-keymaps.outputs.matrix) }}
    steps:
      - name: Download layout build file
        uses: actions/download-artifact@v4
        with:
          name: qmk-layout-artifact-${{ github.run_number }}

      - name: Install keymap-drawer
        run: python3 -m pip install keymap-drawer
      
      - name: Draw keymap and package        
        run: |
          keymap parse -c 10 -q $(echo ${{ matrix.keyboards }} | tr / -).json > keymap.yaml
          keymap draw keymap.yaml > $(echo ${{ matrix.keyboards }} | tr / -).svg

      - name: Cleanup
        run: |
          rm *.json

      - name: Upload rendered keymap
        uses: actions/upload-artifact@v4
        with:
          name: qmk-layout-artifact-${{ github.run_number }}
          overwrite: true
          path: |
            *.svg
            *.json